config/routes.rb
Rails.application.routes.draw do



  resources :fulfillments

  resources :orders

  resources :store_products

  resources :products

  resources :line_items
  resources :carts

  # resources :carts do
  #   resources: :orders
  # end

  # resources :orders do
  #   resources :fulfillments
  # end

  mount ShopifyApp::Engine, at: '/'
  get 'fulfillment/fulfil_order'
  get 'fulfillment/fulfill_order_2'
  post 'fulfillment/fulfill_order_2'

  get 'modal' => "home#modal", :as => :modal
  get 'modal_buttons' => "home#modal_buttons", :as => :modal_buttons
  get 'regular_app_page' => "home#regular_app_page"
  get 'help' => "home#help"
  get 'pagination' => "home#pagination"
  get 'breadcrumbs' => "home#breadcrumbs"
  get 'buttons' => "home#buttons"
  get 'form_page' => "home#form_page"
  post 'form_page' => "home#form_page"
  get 'error' => 'home#error'
  get 'orders' => "home#orders"
  get 'order_old' => "home#order_old"
  get 'fulfill' => "fulfillment#fulfill"


  controller :sessions do
      get 'login' => :new, :as => :login
      post 'login' => :create, :as => :authenticate
      get 'auth/shopify/callback' => :callback
      get 'logout' => :destroy, :as => :logout
  end

  # get 'user_sessions/new'
  # get 'user_sessions/create'
  # get 'user_sessions/destroy'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  # resources :users

  root :to => 'home#index'

  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]

  get "signup_user", to: "users#new", as: "signup_user"
  get "login_user", to: "user_sessions#new", as: "login_user"
  get "logout_user" => "user_sessions#destroy", as: "logout_user"
  # resources :fulfillments
  #
  # resources :orders
  #
  # resources :store_products
  #
  # resources :products

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  # has_one :order

  def add_store_product(store_product)
    current_item = line_items.find_by(store_product_id: store_product.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(store_product_id: store_product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :store_products

end

app/models/fulfillment.rb
class Fulfillment < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :store_product
  belongs_to :cart
  # belongs_to :order

  def total_price
    store_product.price.to_i * quantity.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
  # belongs_to :shop

  has_many :products
  has_many :store_products
  # has_many :line_items

  # belongs_to :cart

  enum product_type: { shopify: 1, manual: 2 }

end

app/models/product.rb
class Product < ApplicationRecord
  # include ShopifyApp::SessionStorage

  # belongs_to :shop
  # attr_accessible :vendor, :title, :product_type




  belongs_to :category, foreign_key: :category_id, class_name: "Category"
  belongs_to :style, foreign_key: :style_id, class_name: "Style"
  #
  #
  attr_accessor :new_category_name
  before_save :create_category_from_name

  # has_many :orders

  # has_one :vendor


  def create_category_from_name
    create_category(name: new_category_name) unless new_category_name.blank?
  end

  attr_accessor :new_style_name
  before_save :create_style_from_name




  def create_style_from_name
    create_category(name: new_style_name) unless new_style_name.blank?
  end

  has_and_belongs_to_many :store_products
  # belongs_to :user_products
  # has_many :user_products

  # belongs_to :vendor_products
  # has_one :vendor_product

end

app/models/session_storage.rb
class SessionStorage

  # < ApplicationRecord

  def self.store(session)
    shop = Shop.find_or_initialize_by(shopify_domain: session.url)
    shop.shopify_token = session.token
    shop.save!
    shop.id
  end

  def self.retrieve(id)
    return unless id
    shop = Shop.find(id)
    ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)
  rescue ActiveRecord::RecordNotFound
    nil
  end

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::SessionStorage
  has_many :store_products
  has_one :user

end

app/models/store_product.rb
class StoreProduct < ApplicationRecord

  before_destroy :not_referenced_by_any_line_item

  belongs_to :product
  has_one :shop

  belongs_to :order

  # before_save :check_product_id
  #
  # def check_product_id
  #   begin
  #     self.store_product_id = @store_product.store_product_id
  #   end while self.class.find_by(store_product_id: store_product_id)
  # end

  has_many :line_items

  private

   def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line items present')
      throw :abort
    end
   end

end

app/models/style.rb
class Style < ApplicationRecord

  has_many :store_products

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  belongs_to :shop, optional: true
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    @webhooks = ShopifyAPI::Webhook.find(:all)
    @store_products = StoreProduct.all
    @orders = Order.all
    @shops = Shop.all
    @fulfillment = ShopifyAPI::Fulfillment.new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def cart_count_over_one
    return total_cart_items if total_cart_items > 0
  end

  def total_cart_items
    total = @cart.line_items.map(&:quantity).sum
    return total if total > 0
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/fulfillment_helper.rb
module FulfillmentHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/home/breadcrumbs.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: 'Breadcrumbs',
        breadcrumb: {
          label: "Regular Page",
          href: "/regular_app_page",
          target: 'app'
        },
        icon: '/shopify.png',
        buttons: {
          secondary: {
            label: "Back",
            href: "/",
            target: 'app'
          }
        }
      });
    });
  </script>
<% end %>

<h1>Breadcrumbs</h1>

<p>In addition to the page title, a single middle level of breadcrumbs can be inserted between the root of the app and the current page. It is defined the same way as a button with label, href, target, loading, etc..</p>

<p>If there is no title set the breadcrumb will not appear.</p>

app/views/home/buttons.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    window.mainPageTitle = 'Buttons Page';
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: window.mainPageTitle,
        buttons: {
          primary: {label: "Primary", loading: false, callback: function(){ alert('Primary clicked'); } },
          secondary: [
            {label: "Normal", loading: false, callback: function(){ alert('Normal clicked'); } },
            {label: "Danger", loading: false, style: 'danger', callback: function(){ alert('Danger clicked'); } },
            {label: "Disabled", loading: false, style: 'disabled', callback: function(){ alert('Disabled clicked'); } }
          ]
        }
      });
    });
  </script>
<% end %>

<p>
  Buttons can be styled as "danger", "disabled", "primary", or null/undefined as default.
</p>

app/views/home/help.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     window.mainPageTitle = 'Help Page';
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.setTitle(window.mainPageTitle);
      ShopifyApp.Bar.loadingOff();
    });
  </script>
<% end %>

<h2>Hey! This is the help page.</h2>

<p>You can go back to the previous page clicking on the breadcrumb link on the top bar. =)</p>

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home" });
    });
  </script>
<% end %>
<h2>Products</h2>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.title, "https://#{@shop_session.url}/admin/products/#{product.id}", target: "_top" %></li>
  <% end %>
</ul>

<hr>



<p id=”notice”><%= notice %></p>

<h2>Webhooks</h2>

<% if @webhooks.present? %>
  <ul>
    <% @webhooks.each do |webhook| %>
      <li><%= webhook.topic %> : <%= webhook.address %></li>
    <% end %>
  </ul>
<% else %>
  <p>This app has not created any webhooks for this Shop. Add webhooks to your ShopifyApp initializer if you need webhooks</p>
<% end %>

<h2>Store Products List</h2>

  <table class="table">
    <thead>
      <tr>
        <th class="center">id</th>
        <th class="center">Product id</th>
        <th class="center">Store Product ID</th>
      </tr>
    </thead>
    <tbody>
      <% @store_products.each do |sp| %>
        <tr>
          <td class="center"><%= sp.id %></td>
          <td class="center"><%= sp.product_id %></td>
          <td class="center"><%= sp.store_product_id %></td>
        </tr>
    </tbody>
    <% end %>
  </table>

  <table class="table">
    <thead>
      <tr>
        <th class="center">id</th>
        <th class="center">Product id</th>
        <th class="center">Store Order ID</th>
        <th class="center">Store Product ID</th>
        <th class="center">Location</th>
        <th class="center">Store Product ID</th>
        <th class="center">Tracking #</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |sp| %>
        <tr>
          <td class="center"><%= sp.id %></td>
          <td class="center"><%= sp.shopify_order_id %></td>
          <td class="center"><%= sp.shopify_product_id %></td>
          <td class="center"><%= sp.shop_id %></td>
          <td class="center"><%= sp.location_id %></td>
          <td class="center"><%= sp.store_product_id %></td>

          <td>
            <% @fulfillment.order_id = sp.shopify_order_id %>
            <%= form_for sp.shopify_order_id do |f| %>
              <%= f.hidden_field location_id: sp.location_id %>
              <%= f.hidden_field line_items: sp.shopify_product_id %>
              <%= f.text_field :tracking_numbers %>
              <%= f.submit %>
            <% end %>
          </td>
          <td>
            <%= button_to 'delete', sp, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %>
          </td>


        </tr>
    </tbody>
    <% end %>
  </table>

  <table class="table">
    <thead>
      <tr>
        <th class="center">id</th>
        <th class="center">Sgop domain</th>
        <th class="center">shop toke</th>
        <th class="center">user</th>
      </tr>
    </thead>
    <tbody>
      <% @shops.each do |shop| %>
        <tr>
          <td class="center"><%= shop.id %></td>
          <td class="center"><%= shop.shopify_domain %></td>
          <td class="center"><%= shop.shopify_token %></td>
          <td class="center"><%= shop.user_id %></td>

        </tr>
    </tbody>
    <% end %>
  </table>



<%= link_to "NP Products", new_product_path %>

<%= link_to "SP Products", new_store_product_path %>

<%= link_to "SP Products Index", store_products_path %>


<%= link_to "New Orders", new_order_path %>


<%= link_to "Orders", orders_path %>

<%= link_to "Fulfillments", new_fulfillment_path %>

<%= link_to "line", new_line_item_path %>

app/views/home/modal.html.erb
<h2>This content is displayed on a modal window!</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tollenda est atque extrahenda radicitus. Animum autem reliquis rebus ita perfecit, ut corpus; Duo Reges: constructio interrete. Dat enim intervalla et relaxat. Igitur neque stultorum quisquam beatus neque sapientium non beatus. Est autem etiam actio quaedam corporis, quae motus et status naturae congruentis tenet;
Quam illa ardentis amores excitaret sui! Cur tandem? Nos commodius agimus. Nihil minus, contraque illa hereditate dives ob eamque rem laetus. Quis enim est, qui non videat haec esse in natura rerum tria? Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Summus dolor plures dies manere non potest? Cum autem in quo sapienter dicimus, id a primo rectissime dicitur. Levatio igitur vitiorum magna fit in iis, qui habent ad virtutem progressionis aliquantum. At ego quem huic anteponam non audeo dicere; Sed venio ad inconstantiae crimen, ne saepius dicas me aberrare;
Quid enim de amicitia statueris utilitatis causa expetenda vides. Quodcumque in mentem incideret, et quodcumque tamquam occurreret. Age nunc isti doceant, vel tu potius quis enim ista melius? Cum id fugiunt, re eadem defendunt, quae Peripatetici, verba. Beatus autem esse in maximarum rerum timore nemo potest. Non dolere, inquam, istud quam vim habeat postea videro; Omnia contraria, quos etiam insanos esse vultis. Duo enim genera quae erant, fecit tria. Ergo, si semel tristior effectus est, hilara vita amissa est?
Videmusne ut pueri ne verberibus quidem a contemplandis rebus perquirendisque deterreantur? Paria sunt igitur. At ego quem huic anteponam non audeo dicere; Ex eorum enim scriptis et institutis cum omnis doctrina liberalis, omnis historia. Mene ergo et Triarium dignos existimas, apud quos turpiter loquare? Ut non sine causa ex iis memoriae ducta sit disciplina. Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Hoc est non modo cor non habere, sed ne palatum quidem. </p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tu quidem reddes; Quis istud possit, inquit, negare?
Cave putes quicquam esse verius. Cave putes quicquam esse verius. Isto modo ne improbos quidem, si essent boni viri. Non quam nostram quidem, inquit Pomponius iocans;
Propter nos enim illam, non propter eam nosmet ipsos diligimus. Non igitur de improbo, sed de callido improbo quaerimus, qualis Q. Ut optime, secundum naturam affectum esse possit. Duo Reges: constructio interrete. Quae quidem vel cum periculo est quaerenda vobis;
Prodest, inquit, mihi eo esse animo. Eaedem res maneant alio modo. Bonum patria: miserum exilium. In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret. </p> 

app/views/home/modal_buttons.html.erb
<h2>This content is content is an iframe.</h2>

<p>
  Modals accept an object of buttons. The object can contain keys as follows:

  <ul>
    <li>`primary`: Max 2 button. Floated right. Defaults to green, and the only button that can be green.</li>
    <li>`secondary`: Max 2 buttons. Floated right after the primary button.</li>
    <li>`tertiary`: Max 2 buttons. Floated left.</li>
  </ul>
</p>

app/views/home/orders.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Shopify Embedded Example App</title>
    <%= stylesheet_link_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>












<% content_for :javascript do %>
  <!-- <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        // icon: "<%= asset_path('') %>",
        pagination: {
          previous: <%= (@previous_page.present? ? {href: @previous_page} : nil).to_json.html_safe %>,
          next: <%= (@next_page.present? ? {href: @next_page} : nil).to_json.html_safe %>
        }
      });
    });
  </script> -->
<% end %>

<div class="section">
  <div class="section-content">
    <div class="section-row">
      <div class="section-listing">
        <div class="section-options">
          <ul class="section-tabs">
            <li class="active"><a href="#top">All Orders</a></li>
          </ul>
          <div class="section-content">
            <div class="section-row">
            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/pagination.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    window.mainPageTitle = 'Pagination (<%= @page %> of <%= @total_pages %>)';
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: window.mainPageTitle,
        icon: '/shopify.png',
        buttons: {
          secondary: {
            label: "Back",
            href: "/",
            target: 'app'
          }
        },
        pagination: {
          previous: <%= (@previous_page.present? ? {href: @previous_page} : nil).to_json.html_safe %>,
          next: <%= (@next_page.present? ? {href: @next_page} : nil).to_json.html_safe %>
        }
      });
    });
  </script>
<% end %>
<h1>Pagination</h1>
<p>Now viewing page <%= @page %> of <%= @total_pages %>.</p>
<p>Pagination links at the top page can load a passed in URL or a Javascript callback.</p>

app/views/home/regular_app_page.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    window.mainPageTitle = 'Regular Page';
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: window.mainPageTitle,
        buttons: {
          secondary: [
            {
              label: "Documentation",
              href: "http://docs.shopify.com/embedded-app-sdk",
              target: 'new'
            },
            {
              label: "Back",
              href: "/",
              target: 'app'
            }
          ]
        }
      });
    });
  </script>
<% end %>

<h2>Regular application page with different top bar</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Primum in nostrane potestate est, quid meminerimus? Mihi quidem Antiochum, quem audis, satis belle videris attendere. Nummus in Croesi divitiis obscuratur, pars est tamen divitiarum. Earum etiam rerum, quas terra gignit, educatio quaedam et perfectio est non dissimilis animantium. At hoc in eo M. Duo Reges: constructio interrete. Quia nec honesto quic quam honestius nec turpi turpius. Nihilne te delectat umquam -video, quicum loquar-, te igitur, Torquate, ipsum per se nihil delectat? Dicimus aliquem hilare vivere;
Et ille ridens: Video, inquit, quid agas; Esse enim quam vellet iniquus iustus poterat inpune. In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret. Et ille ridens: Video, inquit, quid agas; Quid est, quod ab ea absolvi et perfici debeat? Quid ergo? Quod cum dixissent, ille contra. Ille enim occurrentia nescio quae comminiscebatur; Qua ex cognitione facilior facta est investigatio rerum occultissimarum.
Cur tantas regiones barbarorum pedibus obiit, tot maria transmisit? Superiores tres erant, quae esse possent, quarum est una sola defensa, eaque vehementer. Omnia peccata paria dicitis. Nam quid possumus facere melius?
Mihi vero, inquit, placet agi subtilius et, ut ipse dixisti, pressius. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere. Hinc ceteri particulas arripere conati suam quisque videro voluit afferre sententiam. Qui autem esse poteris, nisi te amor ipse ceperit? Non quam nostram quidem, inquit Pomponius iocans; Hanc quoque iucunditatem, si vis, transfer in animum; </p>