config/routes.rb
Rails.application.routes.draw do



  resources :fulfillments

  resources :orders

  resources :store_products

  resources :products

  resources :line_items
  resources :carts

  # resources :carts do
  #   resources: :orders
  # end

  # resources :orders do
  #   resources :fulfillments
  # end

  mount ShopifyApp::Engine, at: '/'
  get 'fulfillment/fulfil_order'
  get 'fulfillment/fulfill_order_2'
  post 'fulfillment/fulfill_order_2'

  get 'modal' => "home#modal", :as => :modal
  get 'modal_buttons' => "home#modal_buttons", :as => :modal_buttons
  get 'regular_app_page' => "home#regular_app_page"
  get 'help' => "home#help"
  get 'pagination' => "home#pagination"
  get 'breadcrumbs' => "home#breadcrumbs"
  get 'buttons' => "home#buttons"
  get 'form_page' => "home#form_page"
  post 'form_page' => "home#form_page"
  get 'error' => 'home#error'
  get 'orders' => "home#orders"
  get 'order_old' => "home#order_old"
  get 'fulfill' => "fulfillment#fulfill"


  controller :sessions do
      get 'login' => :new, :as => :login
      post 'login' => :create, :as => :authenticate
      get 'auth/shopify/callback' => :callback
      get 'logout' => :destroy, :as => :logout
  end

  # get 'user_sessions/new'
  # get 'user_sessions/create'
  # get 'user_sessions/destroy'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  # resources :users

  root :to => 'home#index'

  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]

  get "signup_user", to: "users#new", as: "signup_user"
  get "login_user", to: "user_sessions#new", as: "login_user"
  get "logout_user" => "user_sessions#destroy", as: "logout_user"
  # resources :fulfillments
  #
  # resources :orders
  #
  # resources :store_products
  #
  # resources :products

end

app/models/fulfillment.rb
class Fulfillment < ApplicationRecord
end

app/controllers/fulfillments_controller.rb
class FulfillmentsController < ShopifyApp::AuthenticatedController
  # before_action :set_fulfillment, only: [:show, :edit, :update, :destroy]

  # GET /fulfillments
  # GET /fulfillments.json
  # def index
  #   @fulfillments = Fulfillment.all
  # end

  # GET /fulfillments/1
  # GET /fulfillments/1.json
  # def show
  # end

  # GET /fulfillments/new
  def new
    @orders = Order.all
    @order = Order.find_by(params[:order_id])

    # @order = Order.find_by(params[:shopify_order_id])
    # @shops = Shop.all
    ShopifyAPI::Fulfillment.new(order_number: @order.shopify_order_id,
                               location_id: @order.location_id,
                               line_items: @order.shopify_product_id,
                               tracking_numbers: @order.tracking_numbers)
  end

  # GET /fulfillments/1/edit
  def edit
  end

  # POST /fulfillments
  # POST /fulfillments.json
  def create
    # @fulfillment = Fulfillment.new(fulfillment_params)
    @orders = Order.all
    @order = Order.find_by(params[:order_id])
    # @shops = Shop.all
    ShopifyAPI::Fulfillment.new(order_number: @order.shopify_order_id,
                                               location_id: @order.location_id,
                                               line_items: @order.shopify_product_id,
                                               tracking_numbers: @order.tracking_numbers)

    respond_to do |format|
      if @fulfillment.save
        format.html { redirect_to @fulfillment, notice: 'Fulfillment was successfully created.' }
        format.json { render :show, status: :created, location: @fulfillment }
      else
        format.html { render :new }
        format.json { render json: @fulfillment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fulfillments/1
  # PATCH/PUT /fulfillments/1.json
  def update
    respond_to do |format|
      if @fulfillment.update(fulfillment_params)
        format.html { redirect_to @fulfillment, notice: 'Fulfillment was successfully updated.' }
        format.json { render :show, status: :ok, location: @fulfillment }
      else
        format.html { render :edit }
        format.json { render json: @fulfillment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fulfillments/1
  # DELETE /fulfillments/1.json
  def destroy
    @fulfillment.destroy
    respond_to do |format|
      format.html { redirect_to fulfillments_url, notice: 'Fulfillment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fulfillment
      @fulfillment = Fulfillment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fulfillment_params
      params.fetch(:fulfillment, {}).permit(:order_number, :location_id, :line_items, :tracking_numbers)
    end
end

app/helpers/fulfillment_helper.rb
module FulfillmentHelper
end

app/helpers/fulfillments_helper.rb
module FulfillmentsHelper
end

app/views/fulfillments/_form.html.erb
<%= form_with(model: fulfillment, local: true) do |form| %>
  <% if fulfillment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fulfillment.errors.count, "error") %> prohibited this fulfillment from being saved:</h2>

      <ul>
      <% fulfillment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fulfillments/edit.html.erb
<h1>Editing Fulfillment</h1>

<%= render 'form', fulfillment: @fulfillment %>

<%= link_to 'Show', @fulfillment %> |
<%= link_to 'Back', fulfillments_path %>

app/views/fulfillments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fulfillments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fulfillments.each do |fulfillment| %>
      <tr>
        <td><%= link_to 'Show', fulfillment %></td>
        <td><%= link_to 'Edit', edit_fulfillment_path(fulfillment) %></td>
        <td><%= link_to 'Destroy', fulfillment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fulfillment', new_fulfillment_path %>

app/views/fulfillments/new.html.erb
<h1>New Fulfillment</h1>

<table class="table">
  <thead>
    <tr>
      <th class="center">id</th>
      <th class="center">Product id</th>
      <th class="center">Store Order ID</th>
      <th class="center">Store Product ID</th>
      <th class="center">Location</th>
      <th class="center">Tracking #</th>


    </tr>
  </thead>
  <tbody>
    <% @orders.each do |sp| %>
      <tr>
        <td class="center"><%= sp.id %></td>
        <td class="center"><%= sp.shopify_order_id %></td>
        <td class="center"><%= sp.shopify_product_id %></td>
        <td class="center"><%= sp.shop_id %></td>
        <td class="center"><%= sp.location_id %></td>
        <td>
          <% sp_order_id = sp.shopify_order_id %>
          <%= form_for sp do |f| %>
            <%= f.text_field :tracking_numbers %>
            <%= f.submit %>
          <% end %>
        </td>
      </tr>
  </tbody>
  <% end %>
</table>

app/views/fulfillments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fulfillment_path(@fulfillment) %> |
<%= link_to 'Back', fulfillments_path %>