config/routes.rb
Rails.application.routes.draw do



  resources :fulfillments

  resources :orders

  resources :store_products

  resources :products

  resources :line_items
  resources :carts

  # resources :carts do
  #   resources: :orders
  # end

  # resources :orders do
  #   resources :fulfillments
  # end

  mount ShopifyApp::Engine, at: '/'
  get 'fulfillment/fulfil_order'
  get 'fulfillment/fulfill_order_2'
  post 'fulfillment/fulfill_order_2'

  get 'modal' => "home#modal", :as => :modal
  get 'modal_buttons' => "home#modal_buttons", :as => :modal_buttons
  get 'regular_app_page' => "home#regular_app_page"
  get 'help' => "home#help"
  get 'pagination' => "home#pagination"
  get 'breadcrumbs' => "home#breadcrumbs"
  get 'buttons' => "home#buttons"
  get 'form_page' => "home#form_page"
  post 'form_page' => "home#form_page"
  get 'error' => 'home#error'
  get 'orders' => "home#orders"
  get 'order_old' => "home#order_old"
  get 'fulfill' => "fulfillment#fulfill"


  controller :sessions do
      get 'login' => :new, :as => :login
      post 'login' => :create, :as => :authenticate
      get 'auth/shopify/callback' => :callback
      get 'logout' => :destroy, :as => :logout
  end

  # get 'user_sessions/new'
  # get 'user_sessions/create'
  # get 'user_sessions/destroy'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  # resources :users

  root :to => 'home#index'

  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]

  get "signup_user", to: "users#new", as: "signup_user"
  get "login_user", to: "user_sessions#new", as: "login_user"
  get "logout_user" => "user_sessions#destroy", as: "logout_user"
  # resources :fulfillments
  #
  # resources :orders
  #
  # resources :store_products
  #
  # resources :products

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :store_product
  belongs_to :cart
  # belongs_to :order

  def total_price
    store_product.price.to_i * quantity.to_i
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ShopifyApp::AuthenticatedController
  include CurrentCart
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  # before_action :check_orders, only: [:update, :show, :create]

  before_action :set_cart, only: [:create]


  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
    # @store_products = StoreProduct.all
    # @products = Product.all

  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    # @store_product = StoreProduct.find(params[:store_product_id])
    # @store_products = StoreProduct.all
    # @products = Product.all

    store_product = StoreProduct.find(params[:store_product_id])
    # @product = Product.find(params[:product_id])

    # @order.product_id = @product.id
    # @order.store_product_id = @store_product.id
    # @line_item = LineItem.new(line_item_params)
    @line_item = @cart.add_store_product(store_product)


    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart , notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:store_product_id, :product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>

  <div class="form-inputs">
    <%= f.association :store_product %>
    <%= f.association :cart %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<div class="columns align-items-center">
  <div class="column is-1">
    <%= line_item.quantity %>
  </div>

  <div class="column is-9">
    <strong><%= line_item.store_product.id %></strong>
    <div class="columns align-items-center">
      <div class="content column is-9">
        <%= line_item.store_product.id %>
      </div>
    </div>
  </div>
</div>

<div class="has-text-right">
  <%= link_to 'Remove Item', line_item, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-small mb4" %>
</div>

<hr/ >

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Store product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.store_product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store product:</strong>
  <%= @line_item.store_product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>